# Generated by Django 5.2.13 on 2026-04-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da IA')),
                ('provider_url', models.URLField(default='https://api.openai.com/v1/chat/completions')),
                ('model_name', models.CharField(default='gpt-4o', max_length=50)),
                ('api_key', models.CharField(help_text='Sua chave de API', max_length=255)),
                ('system_prompt', models.TextField(help_text='Defina aqui as memórias, tom de voz e regras de comportamento.')),
                ('temperature', models.FloatField(default=0.7, help_text='0.0 mais focado, 1.0 mais criativo')),
                ('max_tokens', models.IntegerField(default=500)),
            ],
        ),
    ]
