# Generated by Django 5.2.13 on 2026-04-07 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconfig',
            name='api_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='model_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='provider_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='system_prompt',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='temperature',
            field=models.FloatField(default=0.7),
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='Nova conexão na Wired', max_length=200)),
                ('ai_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bots.aiconfig')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bots.chatsession')),
            ],
        ),
    ]
